# Generated by Django 5.0.7 on 2024-07-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.TextField(default=''),
        ),
    ]
