# Generated by Django 5.0.7 on 2024-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0002_project_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='large_projects')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('project_details', models.TextField()),
            ],
        ),
    ]
