# Generated by Django 5.0.7 on 2024-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0003_largeproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeproject',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
