# Generated by Django 4.1 on 2024-08-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0005_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
