# Generated by Django 4.2.10 on 2024-08-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0006_delete_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largeproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='largeproject',
            name='name',
        ),
    ]
