# Generated by Django 4.2.10 on 2024-08-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunray', '0007_remove_largeproject_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largeproject',
            name='project_details',
        ),
    ]
